package com.camilolopes.core.exception.enums;

public enum EbookMessageResponse {

	ERROR_UNEXPECTED, 
	EBOOK_IMAGE_NOT_FOUND, 
	SUMMARY_NOT_FOUND, 
	TITLE_DUPLICATED, 
	INFORMATION_CANNOT_BE_SAVED, 
	EBOOK_CANNOT_BE_REMOVED, 
	EBOOK_CANNOT_BE_LISTED, 
	EBOOK_INSERT_SUCCESS, 
	EBOOK_EDIT_SUCCESS, 
	EBOOK_REMOVE_SUCCESS;

}